export const RPLIntakeData = {
  CPC31420: {
    qualification: "CPC31420-Certificate III in Construction Waterproofing",
    competencies: [
      "Apply waterproofing remedial processes",
      "Apply waterproofing process to external above-ground wet areas",
      "Apply waterproofing process to internal wet areas",
      "Apply waterproofing system to below ground level wet areas",
      "Prepare surfaces for waterproofing application",
      "Use waterproofing tools and equipment",
      "Handle waterproofing materials and components",
      "Apply WHS requirements, policies and procedures in the construction industry",
      "Carry out measurements and calculations",
      "Read and interpret plans and specifications",
      "Conduct workplace communication",
      "Plan and organise work",
      "Work effectively and sustainably in the construction industry",
      "Carry out concreting to simple forms",
      "Carry out basic demolition",
      "Apply basic levelling procedures",
      "Manage finances for new business ventures",
      "Investigate business opportunities",
      "Assess construction waterproofing processes",
    ],
  },
  CPC40920: {
    qualification: "CPC40920-Certificate IV in Plumbing and Services",
    competencies: [
      "Establish legal and risk management requirements of new business ventures",
      "Plan finances for new business ventures",
      "Read and interpret plans and specifications",
      "Resolve business disputes",
      "Carry out WHS requirements",
      "Carry out work-based risk control processes",
      "Estimate and cost work",
      "Access and interpret regulatory requirements for the plumbing and services industry",
      "Design and size sanitary drainage systems",
      "Design and size stormwater drainage systems",
      "Design and size domestic treatment plant disposal systems",
      "Design and size consumer gas installations",
      "Design and size roof drainage systems",
      "Design and size sanitary plumbing systems",
      "Design and size heated and cold-water services and systems",
    ],
  },
  CPC30620: {
    qualification: "CPC30620-Certificate III in Painting and Decorating",
    competencies: [
      "Investigate business opportunities",
      "Organise finances for new business ventures",
      "Erect and dismantle restricted height scaffolding",
      "Work safely at heights",
      "Operate elevated work platforms up to 11 metres",
      "Calculate costs of construction work",
      "Work effectively and sustainably in the construction industry",
      "Plan and organise work",
      "Conduct workplace communication",
      "Carry out measurements and calculations",
      "Read and interpret plans and specifications",
      "Erect and maintain trestle and plank systems",
      "Handle and store painting and decorating materials",
      "Use painting and decorating tools and equipment",
      "Remove and replace doors and door and window components",
      "Prepare existing coated surface for painting",
      "Apply paint by brush and roller",
      "Apply texture coat paint finishes by brush, roller and spray",
      "Apply paint by spray",
      "Match specific paint colours",
      "Apply stains and clear timber finishes",
      "Remove and apply wallpaper",
      "Apply decorative paint finishes",
      "Apply protective paint coating systems",
      "Work safely with lead-painted surfaces in the painting industry",
      "Prepare uncoated surfaces for painting",
      "Work safely to encapsulate non-friable asbestos in the painting industry",
      "Apply WHS requirements, policies and procedures in the construction industry",
      "Design colour schemes for interior and exterior spaces",
    ],
  },
  CPC50220: {
    qualification: "CPC50220-Diploma of Building and Construction (Building)",
    competencies: [
      "Manage business risk",
      "Manage project quality",
      "Manage project stakeholder engagement",
      "Lead WHS risk management",
      "Apply building codes and standards to the construction process for Class 1 and 10 buildings",
      "Select, prepare and administer a construction contract",
      "Identify and produce estimated costs for building and construction projects",
      "Produce labour and material schedules for ordering",
      "Supervise site communication and administration processes for building and construction projects",
      "Apply legal requirements to building and construction projects",
      "Apply structural principles to residential and commercial constructions",
      "Read and interpret plans and specifications",
      "Prepare and evaluate tender documentation",
      "Prepare simple building sketches and drawings",
      "Apply site surveys and set-out procedures to building and construction projects",
      "Lead and manage teams in the building and construction industry",
      "Apply building codes and standards to the construction process for Class 2 to 9 Type C buildings",
      "Apply building codes and standards to the construction process for Type B construction",
      "Monitor costing systems on complex building and construction projects",
      "Supervise the planning of on-site building and construction work",
      "Select and manage building and construction contractors",
      "Administer the legal obligations of a building and construction contractor",
      "Manage construction work",
      "Manage environmental management practices and processes in building and construction",
      "Manage professional technical and legal reports on building and construction projects",
      "Apply structural principles to the construction of buildings up to three storeys",
      "Manage building and construction business finances",
    ],
  },
};
