export const RPLIntakeData = {
  CPC31420: {
    qualification: "CPC31420-Certificate III in Construction Waterproofing",
    competencies: [
      "Apply waterproofing remedial processes",
      "Apply waterproofing process to external above-ground wet areas",
      "Apply waterproofing process to internal wet areas",
      "Apply waterproofing system to below ground level wet areas",
      "Prepare surfaces for waterproofing application",
      "Use waterproofing tools and equipment",
      "Handle waterproofing materials and components",
      "Apply WHS requirements, policies and procedures in the construction industry",
      "Carry out measurements and calculations",
      "Read and interpret plans and specifications",
      "Conduct workplace communication",
      "Plan and organise work",
      "Work effectively and sustainably in the construction industry",
      "Carry out concreting to simple forms",
      "Carry out basic demolition",
      "Apply basic levelling procedures",
      "Manage finances for new business ventures",
      "Investigate business opportunities",
      "Assess construction waterproofing processes",
    ],
  },
  CPC40920: {
    qualification: "CPC40920-Certificate IV in Plumbing and Services",
    competencies: [
      "Establish legal and risk management requirements of new business ventures",
      "Plan finances for new business ventures",
      "Read and interpret plans and specifications",
      "Resolve business disputes",
      "Carry out WHS requirements",
      "Carry out work-based risk control processes",
      "Estimate and cost work",
      "Access and interpret regulatory requirements for the plumbing and services industry",
      "Design and size sanitary drainage systems",
      "Design and size stormwater drainage systems",
      "Design and size domestic treatment plant disposal systems",
      "Design and size consumer gas installations",
      "Design and size roof drainage systems",
      "Design and size sanitary plumbing systems",
      "Design and size heated and cold-water services and systems",
    ],
  },
  CPC30220: {
    qualification: "CPC30220-Certificate III in Carpentry",
    competencies: [
      "Work safely at heights",
      "Erect and dismantle restricted height scaffolding",
      "Apply basic levelling procedures",
      "Erect and dismantle formwork for footings and slabs on ground",
      "Read and interpret plans, specifications and drawings for carpentry work",
      "Install lining, panelling and moulding",
      "Install curtain walling",
      "Erect and dismantle jump form formwork",
      "Erect and dismantle formwork to suspended slabs, columns, beams and walls",
      "Construct, erect and dismantle formwork for stairs and ramps",
      "Install exterior cladding",
      "Construct and install bulkheads",
      "Construct, assemble and install timber external stairs",
      "Construct advanced roofs",
      "Construct eaves",
      "Construct pitched roofs",
      "Erect roof trusses",
      "Construct ceiling frames",
      "Construct and erect wall frames",
      "Install flooring systems",
      "Carry out setting out",
      "Carry out general demolition of minor building structures",
      "Handle carpentry materials",
      "Use carpentry tools and equipment",
      "Carry out concreting to simple forms",
      "Work effectively and sustainably in the construction industry",
      "Conduct workplace communication",
      "Carry out measurements and calculations",
      "Perform construction calculations to determine carpentry material requirements",
      "Carry out levelling operations",
      "Apply WHS requirements, policies and procedures in the construction industry",
      "Identify construction work hazards and select risk control strategies",
    ],
  },
  CPC30620: {
    qualification: "CPC30620-Certificate III in Painting and Decorating",
    competencies: [
      "Investigate business opportunities",
      "Organise finances for new business ventures",
      "Erect and dismantle restricted height scaffolding",
      "Work safely at heights",
      "Operate elevated work platforms up to 11 metres",
      "Calculate costs of construction work",
      "Work effectively and sustainably in the construction industry",
      "Plan and organise work",
      "Conduct workplace communication",
      "Carry out measurements and calculations",
      "Read and interpret plans and specifications",
      "Erect and maintain trestle and plank systems",
      "Handle and store painting and decorating materials",
      "Use painting and decorating tools and equipment",
      "Remove and replace doors and door and window components",
      "Prepare existing coated surface for painting",
      "Apply paint by brush and roller",
      "Apply texture coat paint finishes by brush, roller and spray",
      "Apply paint by spray",
      "Match specific paint colours",
      "Apply stains and clear timber finishes",
      "Remove and apply wallpaper",
      "Apply decorative paint finishes",
      "Apply protective paint coating systems",
      "Work safely with lead-painted surfaces in the painting industry",
      "Prepare uncoated surfaces for painting",
      "Work safely to encapsulate non-friable asbestos in the painting industry",
      "Apply WHS requirements, policies and procedures in the construction industry",
      "Design colour schemes for interior and exterior spaces",
    ],
  },
  CPC50220: {
    qualification: "CPC50220-Diploma of Building and Construction (Building)",
    competencies: [
      "Manage business risk",
      "Manage project quality",
      "Manage project stakeholder engagement",
      "Lead WHS risk management",
      "Apply building codes and standards to the construction process for Class 1 and 10 buildings",
      "Select, prepare and administer a construction contract",
      "Identify and produce estimated costs for building and construction projects",
      "Produce labour and material schedules for ordering",
      "Supervise site communication and administration processes for building and construction projects",
      "Apply legal requirements to building and construction projects",
      "Apply structural principles to residential and commercial constructions",
      "Read and interpret plans and specifications",
      "Prepare and evaluate tender documentation",
      "Prepare simple building sketches and drawings",
      "Apply site surveys and set-out procedures to building and construction projects",
      "Lead and manage teams in the building and construction industry",
      "Apply building codes and standards to the construction process for Class 2 to 9 Type C buildings",
      "Apply building codes and standards to the construction process for Type B construction",
      "Monitor costing systems on complex building and construction projects",
      "Supervise the planning of on-site building and construction work",
      "Select and manage building and construction contractors",
      "Administer the legal obligations of a building and construction contractor",
      "Manage construction work",
      "Manage environmental management practices and processes in building and construction",
      "Manage professional technical and legal reports on building and construction projects",
      "Apply structural principles to the construction of buildings up to three storeys",
      "Manage building and construction business finances",
    ],
  },
  CPC40120: {
    qualification: "CPC40120-Certificate IV in Building and Construction",
    competencies: [
      "Manage finances for new business ventures",
      "Apply project quality management techniques",
      "Apply building codes and standards to the construction process for Class 1 and 10 buildings",
      "Manage work health and safety in the building and construction workplace",
      "Select, prepare and administer a construction contract",
      "Identify and produce estimated costs for building and construction projects",
      "Produce labour and material schedules for ordering",
      "Select, procure and store construction materials for building and construction projects",
      "Plan building and construction work",
      "Supervise site communication and administration processes for building and construction projects",
      "Apply legal requirements to building and construction projects",
      "Apply structural principles to residential and commercial constructions",
      "Read and interpret plans and specifications",
      "Prepare simple building sketches and drawings",
      "Apply site surveys and set-out procedures to building and construction projects",
      "Minimise waste on the building and construction site",
      "Resolve business disputes",
      "Apply building codes and standards to the construction process for Class 2 to 9 Type C buildings",
      "Use building science principles to construct energy efficient buildings",
    ],
  },
  CPC31020: {
    qualification: "CPC31020-Certificate III in Solid Plastering",
    competencies: [
      "Apply WHS requirements, policies and procedures in the construction industry",
      "Apply plaster by projection machine",
      "Install pre-cast decorative mouldings",
      "Restore and renovate solid plasterwork",
      "Apply trowelled texture coat finishes",
      "Apply set coats",
      "Apply float and render to straight and curved surfaces",
      "Prepare surfaces for plastering",
      "Use solid plastering tools and equipment",
      "Read and interpret plans and specifications",
      "Handle solid plastering materials",
      "Carry out measurements and calculations",
      "Conduct workplace communication",
      "Plan and organise work",
      "Work effectively and sustainably in the construction industry",
      "Carry out concreting to simple forms",
      "Erect and dismantle restricted height scaffolding",
      "Apply basic levelling procedures",
      "Manage finances for new business ventures",
      "Investigate business opportunities",
    ],
  },
  CPC32620: {
    qualification: "CPC32620-Certificate III in Roof Plumbing",
    competencies: [
      "Install roof sheets, wall cladding and complex flashings",
      "Install roof coverings to curved roof structures",
      "Install roof components",
      "Fabricate and install external flashings",
      "Fabricate and install roof drainage systems",
      "Collect and store roof water",
      "Select and install roof sheeting and wall cladding",
      "Produce 2-D architectural drawings using design software",
      "Prepare simple drawings",
      "Flash penetrations through roofs and walls",
      "Work safely on roofs",
      "Cut and join sheet metal",
      "Carry out levelling",
      "Carry out WHS requirements",
      "Work effectively in the plumbing services sector",
      "Read plans, calculate quantities and mark out materials",
      "Apply WHS requirements, policies and procedures in the construction industry",
      "Operate personnel and materials hoists",
      "Operate elevated work platforms up to 11 metres",
      "Work safely at heights",
      "Erect and dismantle restricted height scaffolding",
      "Work safely and effectively in manufacturing and engineering",
    ],
  },
  CPC32420: {
    qualification: "CPC32420-Certificate III in Plumbing",
    competencies: [
      "Plan layout and install below ground sanitary drainage systems",
      "Install prefabricated inspection openings and inspection chambers",
      "Install stormwater and sub-soil drainage systems and drain work site",
      "Locate and clear blockages",
      "Install trench support",
      "Prepare simple drawings",
      "Fabricate and install non-ferrous pressure piping",
      "Weld polymer pipes using fusion method",
      "Flash penetrations through roofs and walls",
      "Work safely on roofs",
      "Carry out simple concreting and rendering",
      "Cut using oxy-acetylene equipment",
      "Weld mild steel using oxy-acetylene equipment",
      "Cut and join sheet metal",
      "Carry out levelling",
      "Use plumbing hand and power tools",
      "Handle and store plumbing materials",
      "Carry out WHS requirements",
      "Work effectively in the plumbing services sector",
      "Read plans, calculate quantities and mark out materials",
      "Carry out interactive workplace communication",
      "Operate elevated work platforms up to 11 metres",
      "Work safely at heights",
      "Erect and dismantle restricted height scaffolding",
      "Install on-site domestic wastewater treatment plants and disposal systems",
      "Install LPG storage of aggregate storage capacity exceeding 500 litres and less than 8 kl",
      "Connect and install storage tanks to a domestic water supply",
      "Install pre-treatment facilities",
      "Install discharge pipes",
      "Plan the layout of a residential sanitary plumbing system and fabricate and install sanitary stacks",
      "Install roof components",
      "Fabricate and install external flashings",
      "Fabricate and install roof drainage systems",
      "Collect and store roof water",
      "Set out, install and commission irrigation systems",
      "Design domestic urban irrigation systems",
      "Install and commission Type A gas appliances",
      "Install LPG storage of aggregate storage capacity up to 500 litres",
      "Plan layout and install vacuum drainage systems",
      "Size and install consumer gas piping systems",
      "Install gas sub-meters",
      "Calculate and install natural ventilation for Type A gas appliances",
      "Disconnect and reconnect Type A gas appliances",
      "Purge consumer piping",
      "Install gas appliance flues",
      "Install gas pressure control equipment",
      "Install LPG systems in marine craft",
      "Install LPG systems in caravans, mobile homes and mobile workplaces",
      "Test and maintain fire hydrant and hose reel installations",
      "Install residential life safety sprinkler systems",
      "Fabricate and install fire hydrant and hose reel systems",
      "Set out and install water services",
      "Install and commission water heating systems and adjust controls and devices",
      "Install water pumpsets",
      "Install and fit off sanitary fixtures, water services and adjust water service controls",
      "Install backflow prevention devices",
    ],
  },
  CPC30320: {
    qualification: "CPC30320 Certificate III in Concreting",
    competencies: [
      "Place and fix reinforcement materials",
      "Core concrete",
      "Install topping slabs",
      "Slump-test concrete",
      "Cut concrete",
      "Repair and rectify concrete",
      "Cure concrete",
      "Finish concrete",
      "Place concrete",
      "Determine concrete supply requirements",
      "Select, use and maintain concreting plant, tools and equipment",
      "Handle concreting materials and components",
      "Read and interpret plans and specifications",
      "Carry out measurements and calculations",
      "Conduct workplace communication",
      "Plan and organise work",
      "Work effectively and sustainably in the construction industry",
      "Apply basic levelling procedures",
      "Carry out hand excavation",
      "Erect and dismantle formwork for footings and slabs on ground",
      "Carry out setting out",
      "Apply WHS requirements, policies and procedures in the construction industry",
    ],
  },
};
export const RPLApplicationFormData = {
  CPC30820: {
    title: "RPL Application Form - CPC30820  Certificate III in Roof Tiling",
    programQualification: "RPL-application-form-CPC-30820",
  },
  CPC30620: {
    title: "RPL Application Form - Certificate III in Painting and Decorating",
    programQualification: "RPL-application-form-CPC-30620",
  },
  CPC40920Hydraulic: {
    title:
      "RPL application Form -CPC40920 Certificate IV in plumbing and services (Hydraulic Services Design)",
    programQualification: "RPL-application-form-CPC-40920",
  },
  CPC40920Operations: {
    title:
      "RPL application Form -CPC40920 Certificate IV in plumbing and services (Operations) ",
    programQualification: "RPL-application-form-CPC-40920",
  },
  CPC40120: {
    title:
      "RPL application Form -CPC40120 Certificate IV in building and construction",
    programQualification: "RPL-application-form-CPC-40120",
  },
  CPC31020: {
    title:
      "RPL application Form - CPC31020 Certificate III in Solid Plastering",
    programQualification: "RPL-application-form-CPC-31020",
  },
  CPC32420: {
    title: "RPL application Form- Certificate III in Plumbing",
    programQualification: "RPL-application-form-CPC-32420",
  },
  CPC30220: {
    title: "RPL Application Form - CPC30220 Certificate III in Carpentry",
    programQualification: "RPL-application-form-CPC-30220",
  },
};
